GET http://localhost:3001/api/persons

### 
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Titi4",
    "number":"45678"
}